name: MyJob
on:
  schedule:
  - cron: '0/10 * * * *'
  # Support manual execution
  workflow_dispatch:
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: hello
      run: echo "hello"
    - name: Get new commits
      run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '5 minutes ago' | wc -l)" >> $GITHUB_ENV
    - name: Conditional print
      if: ${{ env.NEW_COMMIT_COUNT > 0 }}
      run: echo "conditional print"
    - name: goodbye
      run: echo "goodbye"
